package com.jdoa.basic.login.dao;


import java.sql.SQLException;
import java.util.List;
import java.util.Set;

import com.jdoa.basic.login.model.TSysUser;

public interface TSysUserDAO {
	
	 public List findAllUserData() throws SQLException;
	  public List findClassificationByuserid(String fid) throws SQLException;
	 public int updateUserDataStatus(TSysUser tSysUser) throws SQLException ;
	
	 
	
	 public List findSysUserClassification(int start,int limit) throws SQLException ;
	
	
	public Set findLoginAllBill(String fId) throws SQLException;
	public Set findLoginAllMaterial(String fId) throws SQLException;
	
	 
	
	  public int countSearchUser(TSysUser sysUser) throws SQLException;
	
	
	 List searchUser(TSysUser sysUser) throws SQLException;
	
	public int updateUserByUserName(TSysUser tSysUser) throws SQLException;
	
	public TSysUser selectUserByName(String username) throws SQLException ;
	
	public Set findLoginAllAuthority(String fid) throws SQLException ;
	
	public List findLoginAllmenu(String fid) throws SQLException ;
	
	public int updateUserPassword(TSysUser tSysUser) throws SQLException;
	
	public TSysUser findUser(TSysUser u)throws SQLException;
    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    void insert(TSysUser record) throws SQLException;
    
  
    
    List selectUserRoleByExample(int start,int limit) throws SQLException ;
 
    List findAllUserToJson()throws SQLException ;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    int updateByPrimaryKey(TSysUser record) throws SQLException;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    int updateByPrimaryKeySelective(TSysUser record) throws SQLException;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    List selectByExample(int start,int limit) throws SQLException;
    
    TSysUser selectUserById(String fId) throws SQLException;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    TSysUser selectByPrimaryKey(String fId) throws SQLException;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    int deleteByExample(String fId) throws SQLException;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    int deleteByPrimaryKey(String fId) throws SQLException;

    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */


    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */


    /**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table ERPCLOUD.T_SYS_USER
	 * 
	 * @abatorgenerated Tue Sep 11 14:53:26 CST 2012
	 */
    int updateByExample(TSysUser record) throws SQLException;
}